#!/bin/bash

declare -a __HELL_PkgManagersArray=("pacman" "pamac" "apt" "dnf" "yum" "zypper")

function __HELL_INFER_PKG_MANAGER {
	if [[ $# -eq 1 ]]
	then
		for x in ${__HELL_PkgManagersArray[@]}
		do
			if command -v "$x" &> /dev/null
			then
				return "$x"
			fi
		done
	fi
	return ""
}

if [[ $# -gt 0 ]]
then
	__HELL_PKGMANAGER=__HELL_INFER_PKG_MANAGER
	if [[ -z "${__HELL_PKGMANAGER}" ]]
	then
		>&2 echo "Too much slipologistic distro. You're not an artist, you make jingles."
		exit 126
	fi

	if [[ "$__HELL_PKGMANAGER" == "$__HELL_PkgManagersArray" ]]
	then
		if command -v "$x" &> /dev/null
		then
			sudo "$__HELL_PKGMANAGER" "-S" "$@" || sudo "pamac" upgrade "$@"
		else
			sudo "$__HELL_PKGMANAGER" "-S" "$@" || sudo "pamac" install "$@"
		fi
	else
		if command -v "$1" &> /dev/null
		then
			if [[ "$__HELL_PKGMANAGER" == "$__HELL_PkgManagersArray[6]" ]]
			then
				sudo "$__HELL_PKGMANAGER" up "$@"
			else
				sudo "$__HELL_PKGMANAGER" upgrade "$@"
			fi
			else
				sudo "$__HELL_PKGMANAGER" install "$@"
			fi
		fi
	fi
else
	>&2 echo -e "Hello newby, u new to computers?"
	exit 1
fi

unset __HELL_PkgManagersArray
unset __HELL_PKGMANAGER