#!/bin/bash

declare -a HellPkgManagersArray=("pamac" "pacman" "apt" "dnf" "yum" "zypper")

function cf_hellpkg {
	if [[ $# -eq 1 ]]
	then
		for x in ${HellPkgManagersArray[@]}
		do
			if command -v $x &> /dev/null
			then
				if [[ $x == "$HellPkgManagersArray[2]" ]]
				then
					sudo $x -S $1
					return 0
				else
					if command -v $x &> /dev/null
					then
						if [[ $x == "$HellPkgManagersArray[6]" ]]
						then
							sudo $x up $1
						else
							sudo $x upgrade $1
						fi
					else
						sudo $x install $1
					fi
					return 0
				fi
			fi
		done
	else
		>&2 echo "Don't fucking arguments list too long with me"
		return 7
	fi
	return 1
}

function is_slipologue_distro {
	for x in ${HellPkgManagersArray[@]}
        do
			if command -v $x &> /dev/null
            then
                return false
        	fi
	done
	return true
}

if [[ $# -gt 0 ]]
then
	if is_slipologue_distro
	then
		>&2 echo "Too much slipologue distro. You're not an artist, you make jingles."
		exit 126
	fi

	for x in "$@"
	do
		t=(which $x)
		if [[ ! -x $t ]]
		then
			cf_hellpkg "$x"
		fi
	done
else
	>&2 echo -e "Hello newby, u new to computers?"
	exit 1
fi

unset HellPkgManagersArray