#!/bin/bash

declare -a __HELL_PkgManagersArray=("pacman" "pamac" "apt" "dnf" "yum" "zypper")

function __HELL_INFER_PKG_MANAGER {
	echo -ne ""
	for x in ${__HELL_PkgManagersArray[@]}
	do
		if command -v "$x" &> /dev/null
		then
			echo -ne "$x"
			break
		fi
	done
}

if [[ $# -gt 0 ]]
then
	__HELL_PKGMANAGER=$(__HELL_INFER_PKG_MANAGER)
	if [[ -z "${__HELL_PKGMANAGER}" ]]
	then
		>&2 echo "Too much slipologistic distro. You're not an artist, you make jingles."
		exit 126
	fi

	for cur_pkg in $@
	do
		if command -v "$x" &> /dev/null
		then
			__HELL_UPDATE_QUEUE="$__HELL_UPDATE_QUEUE $cur_pkg"
		else
			__HELL_INSTALL_QUEUE="$__HELL_INSTALL_QUEUE $cur_pkg"
		fi
	done

	if [[ "$__HELL_PKGMANAGER" == "$__HELL_PkgManagersArray" ]]
	then
		sudo "$__HELL_PKGMANAGER" "-S" "$__HELL_UPDATE_QUEUE $__HELL_INSTALL_QUEUE" || sudo "pamac" upgrade "$__HELL_UPDATE_QUEUE" &&
		sudo "pamac" install "$__HELL_INSTALL_QUEUE"
	else
		if [[ "$__HELL_PKGMANAGER" == "$__HELL_PkgManagersArray[6]" ]]
		then
			sudo "$__HELL_PKGMANAGER" in "$__HELL_INSTALL_QUEUE"
			sudo "$__HELL_PKGMANAGER" up "$__HELL_UPDATE_QUEUE"
		else
			sudo "$__HELL_PKGMANAGER" install "$__HELL_INSTALL_QUEUE"
			sudo "$__HELL_PKGMANAGER" upgrade "$__HELL_UPDATE_QUEUE"
		fi
	fi
else
	>&2 echo -e "Hello newby, u new to computers?"
	exit 1
fi

unset __HELL_PkgManagersArray
unset __HELL_PKGMANAGER