#!/usr/bin/env zsh

__HELLSCRIPTS_INSTALLER_EPIC_FAILED=false
__HELL_OLDPWD=$(pwd)
__HELL_HELLMAP_PATH="$HOME/.zsh_hellmap"

function __HELLSCRIPTS_INJECT_FUNS {
    __HELL_SETUP_LOGGER "Injecting __HELLSCRIPTS_OPEN_EDITOR..."
    function __HELLSCRIPTS_OPEN_EDITOR {
        if [[ $# -eq 0 ]]
        then
            __HELL_EDITOR_FILES=""
        else
            __HELL_EDITOR_FILES="$@"
        fi

        "$EDITOR" "$__HELL_EDITOR_FILES"    ||
        vim "$__HELL_EDITOR_FILES"          ||
        emacs "$__HELL_EDITOR_FILES"        ||
        vifm "$__HELL_EDITOR_FILES"         ||
        nano "$__HELL_EDITOR_FILES"         ||
        vi "$__HELL_EDITOR_FILES"           ||
        ne "$__HELL_EDITOR_FILES"           ||
        __HELL_SETUP_LOGGER "Can't open any editor, configure your EDITOR environment variable." &&
        unset __HELL_EDITOR_FILES                                                            &&
        return 1

        unset __HELL_EDITOR_FILES
    }

    __HELL_SETUP_LOGGER "Injecting __HELLSCRIPTS_UNINSTALL..."
    function __HELLSCRIPTS_UNINSTALL {
        [[ ! -f $__HELL_HELLMAP_PATH ]] && __HELL_REGENERATE_HELLMAP
        . "$__HELL_HELLMAP_PATH"
        rm -rf "$__HELLSCRIPTS_ATTR[MY_REMOTE_REPO_URI]"
        rm -f "$__HELL_HELLMAP_PATH"
    }

    __HELL_SETUP_LOGGER "Injecting __DISPLAY_HELLSCRIPTS_LOGS..."
    function __DISPLAY_HELLSCRIPTS_LOGS {
        cat $__HELLSCRIPTS_ATTR[LOGFILE]
    }

    __HELL_SETUP_LOGGER "Injecting __HELLSCRIPTS_WRITE_LOGS..."
    function __HELLSCRIPTS_WRITE_LOGS {
	__HELL_FIRST_BYTE=$(dd bs=1 count=1 2>/dev/null | od -t o1 -A n | tr -dc 0-9)

        if [[ -z "${__HELL_FIRST_BYTE}" ]]
	then
            return 1
	fi

        if [[ $# -eq 0 ]]
        then
            __HELL_LOG_FILE="$__HELLSCRIPTS_ATTR[LOGFILE]"
        else
            __HELL_LOG_FILE="$1";
        fi

        if [[ $# -gt 1 ]]
        then
            unset __HELL_FIRST_BYTE
            return 7
        fi

        if [[ ! -f "$__HELL_LOG_FILE" ]]
        then
            unset __HELL_FIRST_BYTE
            return 2
        fi

        read l
        if [[ "${l}" ]]
        then
            l="$__HELL_FIRST_BYTE$l"
            echo -e $(date) >> "$__HELL_LOG_FILE"     &&
            2>&1 echo -ne "$l" >> "$__HELL_LOG_FILE"  &&
            while read l
            do
                echo -ne "$l" >> "$__HELL_LOG_FILE" 2>&1
            done
        fi
        echo -e "\n" >> "$__HELL_LOG_FILE"
        unset __HELL_LOG_FILE
    }

    __HELL_SETUP_LOGGER "Injecting __HELLSCRIPTS_INJECT_LOGGER..."
    function __HELLSCRIPTS_INJECT_LOGGER {
        type HelLogger &> /dev/null        && unset -f -- HelLogger
        type HellErrorLogger &> /dev/null  && unset -f -- HellErrorLogger

        function HelLogger {
            if [[ "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]" ]]
            then
                2>&1 $(echo "[HellScripts] ${@}" | __HELLSCRIPTS_WRITE_LOGS)
            fi
        }

        HelLogger "Injected __HELLSCRIPTS_LOGGER..."
        HelLogger "Injecting __HELLSCRIPTS_ERROR_LOGGER..."
        function HellErrorLogger {
            if [[ $__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING] ]]
            then
                $(>&2 echo "[HellScripts ERROR] ${@}" 2>&1 | __HELLSCRIPTS_WRITE_LOGS)
            fi
        }
    }

    __HELL_SETUP_LOGGER "Injecting __HELLSCRIPTS_INJECT_PHONY_LOGGER..."
    function __HELLSCRIPTS_INJECT_PHONY_LOGGER {
        type HelLogger &> /dev/null        && unset -f -- HelLogger
        type HellErrorLogger &> /dev/null  && unset -f -- HellErrorLogger
        __HELL_SETUP_LOGGER "Injecting __HELLSCRIPTS_LOGGER (Name squatting: Phony function)..."  &&
        __HELL_SETUP_LOGGER "Injecting __HELLSCRIPTS_ERROR_LOGGER (Name squatting: Phony function)..."
        function HelLogger {}
        function HellErrorLogger {}
    }

    __HELL_SETUP_LOGGER "Injecting __HELLSCRIPTS_FETCH_PATHES..."
    function __HELLSCRIPTS_FETCH_PATHES {
        __HELLSCRIPTS_DIRS=$(find $__HELLSCRIPTS_ATTR[REPO_DIR] -type d -not -path "$__HELLSCRIPTS_ATTR[REPO_DIR]/.git*")
        echo "${__HELLSCRIPTS_DIRS//[$'\t\r\n']/:}:$HOME/.emacs.d/bin"
        unset __HELLSCRIPTS_DIRS
    }

    __HELL_SETUP_LOGGER "Injecting __HELL_IS_COMMAND_IMPORTED..."
    function __HELL_IS_COMMAND_IMPORTED {
        if [[ $# -eq 0 ]]
        then
            HellErrorLogger "LOL"  &&
            return 7
        fi

        for cmd in $@
        do
            if ! command -v "$cmd" &> /dev/null
            then
                return false
            fi
        done

        true
    }

    __HELL_SETUP_LOGGER "Injecting __HELL_REMOTE_EXECUTION..."
    function HellRemoteExecution {
        if [[ $# -eq 0 ]]
        then
            HellErrorLogger "What should I hellah remote execute? I'm not designed to handle riddles."  &&
            return 7
        fi

        (
            bash <(curl -Ls "$1") "${@: 2}"    ||
            bash <(wget -qO- "$1") "${@: 2}"   ||
            bash <(lynx -dump "$1") "${@: 2}"  ||
            HellErrorLogger "Failed to run command!\nRemote URI: $1\nArguments: ${@: 2}"
        ) | __HELLSCRIPTS_WRITE_LOGS
    }
}

function __HELLSCRIPTS_RUN_INSTALLER {
    function __HELL_SETUP_LOGGER {
        if [[ $# -eq 0 ]]
        then
	        return
	    fi
	    echo "[HellScripts Amnesic Setup Logger]" "${@}"
    }

    __HELL_SETUP_LOGGER "Initializing Setup..."
    function __HELL_EDIT_ZSHRC {
        __HELL_SETUP_LOGGER "Checking your .zshrc..."
        if [[ ! $(cat "$HOME/.zshrc" &>/dev/null | grep "HELLSCRIPTS") ]]
        then
            __HELL_SETUP_LOGGER "No mention of \"HELLSCRIPTS\" found. Injecting..."
            touch "$HOME/.zshrc"
            (
                echo "# [HELLSCRIPTS CONFIG] (uncomment and edit if u wanna ride me)"
		echo "# __HELLSCRIPTS_TMP_FILE=$(mktemp) # * ... This goes at the top of your .zshrc file"
                echo "# . \"$HOME/.zsh_hellmap\" # * ... This goes at the top of your .zshrc file too!"
		echo -e "\n"
                echo "# if \"$__HELLSCRIPTS_ATTR[ENABLE_MANJARO_ZSH_PROMPT_STYLE]\""
                echo "# then"
                echo "#     if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]"
                echo "#     then"
                echo "#         . /usr/share/zsh/manjaro-zsh-prompt"
                echo "#     fi"
                echo "# fi"
                echo -e "\n"
                echo "# if \"$__HELLSCRIPTS_ATTR[ENABLE_MANJARO_ZSH_PROMPT_CONFIG]\""
                echo "# then"
                echo "#     USE_POWERLINE=\"true\""
                echo "#     if [[ -e /usr/share/zsh/manjaro-zsh-config ]]"
                echo "#     then"
                echo "#         . /usr/share/zsh/manjaro-zsh-config"
                echo "#     fi"
                echo "# fi"
                echo -e "\n"
                echo "# if \"$__HELLSCRIPTS_ATTR[HELL_MODE]\""
                echo "# then"
                echo "#     echo \"HellScripts startup logs available at -> $__HELLSCRIPTS_TMP_FILE\""
                echo -e "\n"
                echo "    . \"$__HELLSCRIPTS_ATTR[SETUP_FILEPATH]\" \"doINSTALL\""
                echo "# fi"
            ) >> "$HOME/.zshrc"
            __HELL_SETUP_LOGGER "Injected HellScripts config sample... Opening Editor."
            __HELL_OPEN_EDITOR "$HOME/.zshrc"
    	fi
    }

    function __HELL_REGENERATE_HELLMAP {
        __HELL_SETUP_LOGGER "Building Hellmap anew, reseting your crappy config."
        rm -f "$__HELL_HELLMAP_PATH"
        (
            echo "set -a"                                                                                                           &&
            echo "__HELL_REPO_ROOT=\"$HOME/MyHellScripts\""                                                                         &&
            echo "declare -Ax __HELLSCRIPTS_ATTR=("                                                                                 &&
            echo "    [\"HELL_MODE\"]=true"                                                                                           &&
            echo "    [\"ENABLE_MANJARO_ZSH_PROMPT_STYLE\"]=false"                                                                  &&
            echo "    [\"ENABLE_MANJARO_ZSH_PROMPT_CONFIG\"]=true"                                                                  &&
            echo "    [\"ENABLE_HELLSCRIPTS_UPDATE_ON_SHELL_POP\"]=true"                                                            &&
            echo "    [\"ENABLE_HELLSCRIPTS_MACKUP_BACKUP_ON_SHELL_POP\"]=true"                                                     &&
            echo "    [\"ENABLE_HELLSCRIPTS_LOGGING\"]=true"                                                                        &&
            echo "    [\"ENABLE_HELLSCRIPTS_LOGGER_PROPAGATION\"]=true"                                                             &&
            echo "    [\"ENABLE_SPLASHSCREEN_ON_SHELL_POP\"]=true"                                                                  &&
            echo "    [\"MY_REMOTE_REPO_URI\"]=\"git@github.com:LeBlancLapin/MyHellScripts.git\""                                   &&
            echo "    [\"MY_MACKUP_REMOTE_REPO_URI\"]=\"git@github.com:LeBlancLapin/Mackup.git\""                                   &&
            echo "    [\"PREZTO_REMOTE_REPO_URI\"]=\"https://github.com/sorin-ionescu/prezto.git\""                                 &&
            echo "    [\"REMOTE_GETPKG_SCRIPT_URI\"]=\"https://raw.githubusercontent.com/LeBlancLapin/hell-pkg/main/hell-getpkg\""  &&
            echo "    [\"REPO_DIR\"]=\"$__HELL_REPO_ROOT\""                                                                         &&
            echo "    [\"MACKUP_REPO_DIR\"]=\"$HOME/.config/mackup_backup/Mackup\""                                                 &&
            echo "    [\"PREZTO_REPO_DIR\"]=\"${ZDOTDIR:-$HOME}/.zprezto\""                                                         &&
            echo "    [\"SETUP_FILEPATH\"]=\"$__HELL_REPO_ROOT/sHell/hell-installer\""                                              &&
            echo "    [\"MACKUP_CONFIG_FILEPATH\"]=\"~/.mackup.cfg\""                                                               &&
            echo "    [\"MEMO_RUNTIME_ERROR\"]=false"                                                                               &&
            echo "    [\"LOGFILE\"]=\"$__HELLSCRIPTS_TMP_FILE\""                                                                    &&
            echo ")"                                                                                                                &&
            echo "set +a"
        ) >> "$__HELL_HELLMAP_PATH"

        __HELL_SETUP_LOGGER "Done. See?"
        cat "$__HELL_HELLMAP_PATH"
    }

    if [[ ! -f $__HELL_HELLMAP_PATH ]]
    then
        __HELL_REGENERATE_HELLMAP
        __HELL_EDIT_ZSHRC
    fi

    __HELL_SETUP_LOGGER "Sourcing HellMap..."
    . "$__HELL_HELLMAP_PATH"

    __HELL_SETUP_LOGGER "Injecting HellScripts core functions..."
    __HELLSCRIPTS_INJECT_FUNS

    if [[ "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]" ]]
    then
        __HELLSCRIPTS_INJECT_LOGGER
        HelLogger "Injected HellScripts logger into your Shell env..."
    else
        __HELLSCRIPTS_INJECT_PHONY_LOGGER
        HelLogger "Injected a Phony HellScripts logger into your Shell env..."
    fi

    if ! __HELL_IS_COMMAND_IMPORTED "git"
    then
        HelLogger "Installing git..."  &&
        HellRemoteExecution "$__HELLSCRIPTS_ATTR[REMOTE_GETPKG_SCRIPT_URI]" "git"
    fi

    if ! __HELL_IS_COMMAND_IMPORTED "zsh"
    then
        HelLogger "Installing zsh..."                                              &&
        HellRemoteExecution "$__HELLSCRIPTS_ATTR[REMOTE_GETPKG_SCRIPT_URI]" "zsh"  &&
        chsh -s /bin/zsh
    fi

    if ! __HELL_IS_COMMAND_IMPORTED "curl"
    then
        HelLogger "Installing curl..."  &&
        HellRemoteExecution "$__HELLSCRIPTS_ATTR[REMOTE_GETPKG_SCRIPT_URI]" "curl"
    fi

    if [[ ! $(ps -p $$ | grep zsh) ]]
    then
        HelLogger "Initializing your HellScripts session with zsh..."
        exec zsh
    fi

    if [[ ! -d "$__HELLSCRIPTS_ATTR[REPO_DIR]" ]]
    then
        HelLogger "Importing HellScripts core..."  &&
        cd -P ~                                    &&
        (
            git clone "$__HELLSCRIPTS_ATTR[MY_REMOTE_REPO_URI]" `basename "$__HELLSCRIPTS_ATTR[REPO_DIR]"` --recurse-submodules |
            __HELLSCRIPTS_WRITE_LOGS
        ) || __HELLSCRIPTS_INSTALLER_EPIC_FAILED=true;
    fi

    __HELL_NEW_PATH_ELM=$(eval __HELLSCRIPTS_FETCH_PATHES)
    PATH="$PATH:$__HELL_NEW_PATH_ELM"
    HelLogger "Updated PATH with values: $__HELL_NEW_PATH_ELM"
    unset __HELL_NEW_PATH_ELM

    if [[ $__HELLSCRIPTS_INSTALLER_EPIC_FAILED ]]
    then
        HellErrorLogger "\nWell tried, wkwkwk.\n" \
        "Are you aware this is just a gitmodule which I made public,\n" \
        "only an artefact from a several dozens of thousands lines of code project?\n" \
        "I love u qt."
    else
        . .propagate_hell_zshmess
    fi

    unset __HELLSCRIPTS_INSTALLER_EPIC_FAILED
}

if [[ $# -eq 0 ]]
then
    __HELLSCRIPTS_RUN_INSTALLER
else
    if [[ "$1" == "doINJECT" ]]
    then
        __HELLSCRIPTS_INJECT_FUNS
    fi

    if [[ "$1" == "doINSTALL" ]]
    then
        __HELLSCRIPTS_RUN_INSTALLER
    fi

    if [[ "$1" == "doUNINSTALL" ]]
    then
        __HELLSCRIPTS_UNINSTALL
        __HELLSCRIPTS_RUN_INSTALLER
    fi

    if [[ "$1" == "doREINSTALL" ]]
    then
        __HELLSCRIPTS_UNINSTALL
        __HELLSCRIPTS_RUN_INSTALLER
    fi
fi
